apiVersion: v1
kind: ConfigMap
metadata:
  name: work-order-service-config
data:
  SERVER_PORT: "3002"
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  AWS_REGION: "us-east-2"
  OTEL_ENABLED: "true"
  OTEL_SERVICE_NAME: "work-order-service"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"
