apiVersion: v1
kind: Service
metadata:
  name: work-order-service
  labels:
    app: work-order-service
spec:
  type: ClusterIP
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP
  selector:
    app: work-order-service
